name: Waiting_Time_Prediction

channels:
  - defaults

dependencies:
  - python=3.10.13
  - pip<=21.2.3
  - pip:
    - mlflow==2.15.1
    - cloudpickle==3.0.0
    - numpy==1.26.4
    - psutil==6.0.0
    - scikit-learn==1.5.1
    - scipy==1.14.0